apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-controller
  labels:
    name: myapp
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        visualize: "true"
        name: myapp
        app: myapp-test
        uses: myapp-service
    spec:
      containers:
        - name: myapp
          image: firog/test-app
          resources:
            requests:
              memory: "1Gi"
              # cpu: "1"
          ports:
            - name: http
              containerPort: 5000
          # volumeMounts:
          #   - name: myapp-persistent-deploy
          #     mountPath: /work
        - name: kubectl
          image: firog/kubectl
          args: ["proxy","-p","8001"]
      # volumes:
      #   - name: myapp-persistent-deploy
      #     gcePersistentDisk:
      #       pdName: caw
      #       fsType: ext4
            # readOnly: true
