apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    name: myapp
    app: myapp
    visualize: "true"
spec:
  type: LoadBalancer
  selector:
    name: myapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http
