apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-controller
  labels:
    name: myapp
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        visualize: "true"
        name: myapp
        app: myapp-test
        uses: myapp-service
    spec:
      containers:
        - name: myapp
          image: firog/test-app
          ports:
            - name: http
              containerPort: 5000
        - name: kubectl
          image: firog/kubectl
          args: ["proxy","-p","8001"]
