apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    name: myapp
    app: myapp
    visualize: "true"
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    name: myapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service
#   labels:
#     name: myapp
#     app: myapp
# spec:
#   ports:
#   - name: http
#     targetPort: 80
#     port: 5000
#   selector:
#     name: myapp
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: myapp-service
# spec:
#   rules:
#     - host: myapp.firog.club
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: myapp-service
#               servicePort: 80
