apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    name: myapp
    app: myapp
    visualize: "true"
spec:
  type: LoadBalancer
  # loadBalancerIP: 104.155.62.244
  selector:
    name: myapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http



# Use kubenow and connect to cluster over localhost instead
