apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    component: test-app
  template:
    metadata:
      labels:
        app: taskQueue
        component: test-app
    spec:
      containers:
      - image: firog/test-app
        name: test-app
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
