apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    name: rabbitmq
    visualise: "true"
spec:
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmqc