apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq-controller
  labels:
    name: rabbitmq
    visualize: "true"
spec:
  replicas: 1
  selector:
    name: rabbitmq
  template:
    metadata:
      labels:
        visualize: "true"
        name: rabbitmq
        app: taskQueue
        uses: rabbitmq-service
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - name: http
              containerPort: 5672