apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    name: rabbitmq
    app: taskQueue
    visualize: "true"
spec:
  selector:
    name: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: http