apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  selector:
    component: rabbitmqc
    name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
        app: taskQueue
        component: rabbitmqc
        uses: rabbitmq-service
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m